### ISSUE TITLE
implicit html mode is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#187]
Running with server mode on a Dart file is broken:

```
dart --checked ./bin/devc.dart --server bar.dart
```

It appears that the problem is the MemoryFileSystem resolver.  In this mode, we create a MemoryFileSystem with an index.html that points to bar.dart. 

But - the MemoryFileSystem always seems to resolve a non-existent file by just creating one on demand.  This is masking the real bar.dart and causing an error afterward:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/git/dev_compiler] dart --checked ./bin/devc.dart --server --port 9500 bar.dart 
Unhandled exception:
Uncaught Error: The null object does not have a getter 'element'.

NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      createSpan (package:dev_compiler/src/utils.dart:437:37)
#3      CheckerReporter._createSpan (package:dev_compiler/src/report.dart:78:17)
#4      SummaryReporter.log (package:dev_compiler/src/report.dart:161:29)
#5      HtmlSourceNode._reportError (package:dev_compiler/src/dependency_graph.dart:218:24)
#6      HtmlSourceNode.update (package:dev_compiler/src/dependency_graph.dart:190:23)
#7      refreshStructureAndMarks.<anonymous closure> (package:dev_compiler/src/dependency_graph.dart:374:41)
#8      visitInPreOrder.helper (package:dev_compiler/src/dependency_graph.dart:460:11)
#9      visitInPreOrder (package:dev_compiler/src/dependency_graph.dart:464:9)
#10     refreshStructureAndMarks (package:dev_compiler/src/dependency_graph.dart:374:18)
#11     rebuild (package:dev_compiler/src/dependency_graph.dart:411:27)
#12     Compiler.run (package:dev_compiler/devc.dart:226:12)
#13     CompilerServer.start.<start_async_body> (package:dev_compiler/devc.dart:309:17)
#14     _RootZone.runUnary (dart:async/zone.dart:1155)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#17     _Future._completeWithValue (dart:async/future_impl.dart:358)
#18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#19     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#20     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

**Comment by jmesserly** [comment]
Hmm, thought I tested this manually. Maybe it was broken at some point, or by the later refactoring to TypeResolver.

> But - the MemoryFileSystem always seems to resolve a non-existent file by just creating one on demand. 

that should be fine. I suspect an ordering issue in URI resolvers, or an issue with ResourceUriProvider

**Comment by jmesserly** [comment]
Ah, ResourceUriResolver matches FileUriResolver ... they both resolve whether or not the file exists. D'oh :)
