### ISSUE TITLE
Checking sky's framework: NoSuchMethodError: method not found: 'isDynamic'

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dev_compiler#200]
* Globally install dev_compiler
* Clone https://github.com/domokit/mojo
* cd mojo/sky/sdk/lib
* dartdevc fn2.dart

Expected: some error about dart:sky not being found.  Which we got :)

Actual: the expected error, but also a crash:

```
~/Code/mojo/sky/sdk/lib/framework[master] $ dartdevc fn2.dart 
severe: line 10, column 1 of fn2.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 5, column 1 of app.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 6, column 1 of rendering/render_box.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 8, column 1 of rendering/render_node.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 6, column 1 of scheduler.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 5, column 1 of rendering/render_block.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 5, column 1 of rendering/render_flex.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 5, column 1 of rendering/render_paragraph.dart: [Message] File dart:sky not found
import 'dart:sky' as sky;
^^^^^^^^^^^^^^^^^^^^^^^^^
severe: line 59, column 3 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  sky.view.scheduleFrame();
  ^^^
severe: line 51, column 12 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
    return sky.window.cancelAnimationFrame(id);
           ^^^
severe: line 6, column 22 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
import 'dart:sky' as sky;
                     ^^^
severe: line 41, column 7 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  if (sky.window != null)
      ^^^
severe: line 50, column 7 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  if (sky.window != null)
      ^^^
severe: line 36, column 10 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  assert(sky.window == null);
         ^^^
severe: line 56, column 10 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  assert(sky.window == null);
         ^^^
severe: line 32, column 3 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  sky.view.setBeginFrameCallback(_beginFrame);
  ^^^
severe: line 42, column 12 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
    return sky.window.requestAnimationFrame(callback);
           ^^^
severe: line 31, column 10 of scheduler.dart: [AnalyzerError] Undefined name 'sky'
  assert(sky.window == null);
         ^^^
severe: line 98, column 14 of rendering/render_node.dart: [AnalyzerError] The method 'markNeedsLayout' is not defined for the class 'AbstractNode'
      parent.markNeedsLayout();
             ^^^^^^^^^^^^^^^
severe: line 229, column 7 of rendering/render_node.dart: [AnalyzerError] The method 'adoptChild' is not defined for the class 'RenderNodeWithChildMixin'
      adoptChild(_child);
      ^^^^^^^^^^
severe: line 264, column 31 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      assert(child.parentData.previousSibling != child);
                              ^^^^^^^^^^^^^^^
severe: line 338, column 24 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      child.parentData.previousSibling.parentData.nextSibling = child.parentData.nextSibling;
                       ^^^^^^^^^^^^^^^
severe: line 251, column 30 of rendering/render_node.dart: [AnalyzerError] The setter 'previousSibling' is not defined for the class 'ParentData'
      nextSibling.parentData.previousSibling = previousSibling;
                             ^^^^^^^^^^^^^^^
severe: line 184, column 22 of rendering/render_node.dart: [AnalyzerError] Undefined class 'sky.PointerEvent'
  void handlePointer(sky.PointerEvent event) {
                     ^^^^^^^^^^^^^^^^
severe: line 31, column 61 of rendering/render_node.dart: [AnalyzerError] 0 positional arguments expected, but 2 found
  RenderNodeDisplayList(double width, double height) : super(width, height);
                                                            ^^^^^^^^^^^^^^^
severe: line 290, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
    assert(child.parentData.nextSibling == null);
                            ^^^^^^^^^^^
severe: line 8, column 22 of rendering/render_node.dart: [AnalyzerError] Undefined name 'sky'
import 'dart:sky' as sky;
                     ^^^
severe: line 357, column 32 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child = child.parentData.nextSibling;
                               ^^^^^^^^^^^
severe: line 340, column 26 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
    if (child.parentData.nextSibling == null) {
                         ^^^^^^^^^^^
severe: line 317, column 26 of rendering/render_node.dart: [AnalyzerError] The setter 'previousSibling' is not defined for the class 'ParentData'
        child.parentData.previousSibling = before.parentData.previousSibling;
                         ^^^^^^^^^^^^^^^
severe: line 345, column 82 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      child.parentData.nextSibling.parentData.previousSibling = child.parentData.previousSibling;
                                                                                 ^^^^^^^^^^^^^^^
severe: line 324, column 34 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
        assert(before.parentData.previousSibling == child);
                                 ^^^^^^^^^^^^^^^
severe: line 381, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
    return child.parentData.nextSibling;
                            ^^^^^^^^^^^
severe: line 273, column 31 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      assert(child.parentData.nextSibling != child);
                              ^^^^^^^^^^^
severe: line 297, column 31 of rendering/render_node.dart: [AnalyzerError] The setter 'nextSibling' is not defined for the class 'ParentData'
        _lastChild.parentData.nextSibling = child;
                              ^^^^^^^^^^^
severe: line 373, column 32 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child = child.parentData.nextSibling;
                               ^^^^^^^^^^^
severe: line 335, column 38 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      _firstChild = child.parentData.nextSibling;
                                     ^^^^^^^^^^^
severe: line 344, column 31 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      assert(child.parentData.nextSibling.parentData is ParentDataType);
                              ^^^^^^^^^^^
severe: line 129, column 36 of rendering/render_node.dart: [AnalyzerError] The getter '_relayoutSubtreeRoot' is not defined for the class 'AbstractNode'
      relayoutSubtreeRoot = parent._relayoutSubtreeRoot;
                                   ^^^^^^^^^^^^^^^^^^^^
severe: line 35, column 5 of rendering/render_node.dart: [AnalyzerError] The method 'translate' is not defined for the class 'RenderNodeDisplayList'
    translate(-position.x, -position.y);
    ^^^^^^^^^
severe: line 32, column 37 of rendering/render_node.dart: [AnalyzerError] Undefined class 'sky.Point'
  void paintChild(RenderNode child, sky.Point position) {
                                    ^^^^^^^^^
severe: line 321, column 33 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
        assert(child.parentData.nextSibling.parentData is ParentDataType);
                                ^^^^^^^^^^^
severe: line 263, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
    while (child.parentData.previousSibling != null) {
                            ^^^^^^^^^^^^^^^
severe: line 230, column 5 of rendering/render_node.dart: [AnalyzerError] The method 'markNeedsLayout' is not defined for the class 'RenderNodeWithChildMixin'
    markNeedsLayout();
    ^^^^^^^^^^^^^^^
severe: line 342, column 37 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      _lastChild = child.parentData.previousSibling;
                                    ^^^^^^^^^^^^^^^
severe: line 226, column 7 of rendering/render_node.dart: [AnalyzerError] The method 'dropChild' is not defined for the class 'RenderNodeWithChildMixin'
      dropChild(_child);
      ^^^^^^^^^
severe: line 323, column 26 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
        child.parentData.nextSibling.parentData.previousSibling = child;
                         ^^^^^^^^^^^
severe: line 322, column 26 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
        child.parentData.previousSibling.parentData.nextSibling = child;
                         ^^^^^^^^^^^^^^^
severe: line 308, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      if (before.parentData.previousSibling == null) {
                            ^^^^^^^^^^^^^^^
severe: line 320, column 33 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
        assert(child.parentData.previousSibling.parentData is ParentDataType);
                                ^^^^^^^^^^^^^^^
severe: line 311, column 26 of rendering/render_node.dart: [AnalyzerError] The setter 'nextSibling' is not defined for the class 'ParentData'
        child.parentData.nextSibling = before;
                         ^^^^^^^^^^^
severe: line 265, column 32 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      child = child.parentData.previousSibling;
                               ^^^^^^^^^^^^^^^
severe: line 337, column 31 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      assert(child.parentData.previousSibling.parentData is ParentDataType);
                              ^^^^^^^^^^^^^^^
severe: line 274, column 32 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child = child.parentData.nextSibling;
                               ^^^^^^^^^^^
severe: line 250, column 37 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
      assert(nextSibling.parentData.previousSibling == this);
                                    ^^^^^^^^^^^^^^^
severe: line 245, column 34 of rendering/render_node.dart: [AnalyzerError] The setter 'nextSibling' is not defined for the class 'ParentData'
      previousSibling.parentData.nextSibling = nextSibling;
                                 ^^^^^^^^^^^
severe: line 338, column 82 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child.parentData.previousSibling.parentData.nextSibling = child.parentData.nextSibling;
                                                                                 ^^^^^^^^^^^
severe: line 272, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
    while (child.parentData.nextSibling != null) {
                            ^^^^^^^^^^^
severe: line 317, column 62 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
        child.parentData.previousSibling = before.parentData.previousSibling;
                                                             ^^^^^^^^^^^^^^^
severe: line 30, column 37 of rendering/render_node.dart: [AnalyzerError] Undefined class 'sky.PictureRecorder'
class RenderNodeDisplayList extends sky.PictureRecorder {
                                    ^^^^^^^^^^^^^^^^^^^
severe: line 365, column 32 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child = child.parentData.nextSibling;
                               ^^^^^^^^^^^
severe: line 294, column 24 of rendering/render_node.dart: [AnalyzerError] The setter 'previousSibling' is not defined for the class 'ParentData'
      child.parentData.previousSibling = _lastChild;
                       ^^^^^^^^^^^^^^^
severe: line 244, column 41 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      assert(previousSibling.parentData.nextSibling == this);
                                        ^^^^^^^^^^^
severe: line 312, column 27 of rendering/render_node.dart: [AnalyzerError] The setter 'previousSibling' is not defined for the class 'ParentData'
        before.parentData.previousSibling = child;
                          ^^^^^^^^^^^^^^^
severe: line 347, column 22 of rendering/render_node.dart: [AnalyzerError] The setter 'previousSibling' is not defined for the class 'ParentData'
    child.parentData.previousSibling = null;
                     ^^^^^^^^^^^^^^^
severe: line 345, column 24 of rendering/render_node.dart: [AnalyzerError] The getter 'nextSibling' is not defined for the class 'ParentData'
      child.parentData.nextSibling.parentData.previousSibling = child.parentData.previousSibling;
                       ^^^^^^^^^^^
severe: line 318, column 26 of rendering/render_node.dart: [AnalyzerError] The setter 'nextSibling' is not defined for the class 'ParentData'
        child.parentData.nextSibling = before;
                         ^^^^^^^^^^^
severe: line 333, column 26 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
    if (child.parentData.previousSibling == null) {
                         ^^^^^^^^^^^^^^^
severe: line 348, column 22 of rendering/render_node.dart: [AnalyzerError] The setter 'nextSibling' is not defined for the class 'ParentData'
    child.parentData.nextSibling = null;
                     ^^^^^^^^^^^
severe: line 291, column 29 of rendering/render_node.dart: [AnalyzerError] The getter 'previousSibling' is not defined for the class 'ParentData'
    assert(child.parentData.previousSibling == null);
                            ^^^^^^^^^^^^^^^
severe: line 33, column 5 of rendering/render_node.dart: [AnalyzerError] The method 'translate' is not defined for the class 'RenderNodeDisplayList'
    translate(position.x, position.y);
    ^^^^^^^^^
Unhandled exception:
The null object does not have a getter 'isDynamic'.

NoSuchMethodError: method not found: 'isDynamic'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      isDynamicTarget (package:dev_compiler/src/utils.dart:211)
#3      RestrictedRules.isDynamicTarget (package:dev_compiler/src/checker/rules.dart:554)
#4      CodeChecker.visitPrefixedIdentifier (package:dev_compiler/src/checker/checker.dart:590)
#5      PrefixedIdentifier.accept (package:analyzer/src/generated/ast.dart:14229)
#6      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:2940)
#7      TypeName.visitChildren (package:analyzer/src/generated/ast.dart:18925)
#8      RecursiveAstVisitor.visitTypeName (package:analyzer/src/generated/ast.dart:15104)
#9      TypeName.accept (package:analyzer/src/generated/ast.dart:18921)
#10     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:2940)
#11     ExtendsClause.visitChildren (package:analyzer/src/generated/ast.dart:7078)
#12     RecursiveAstVisitor.visitExtendsClause (package:analyzer/src/generated/ast.dart:14731)
#13     ExtendsClause.accept (package:analyzer/src/generated/ast.dart:7074)
#14     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:2940)
#15     ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4247)
#16     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/src/generated/ast.dart:14605)
#17     CodeChecker.visitClassDeclaration (package:dev_compiler/src/checker/checker.dart:389)
#18     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4181)
#19     NodeList.accept (package:analyzer/src/generated/ast.dart:12237)
#20     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4799)
#21     CodeChecker.visitCompilationUnit (package:dev_compiler/src/checker/checker.dart:357)
#22     Compiler._buildDartLibrary (package:dev_compiler/devc.dart:187)
#23     Compiler._buildSource (package:dev_compiler/devc.dart:112)
#24     rebuild.<anonymous closure> (package:dev_compiler/src/dependency_graph.dart:439)
#25     visitInPostOrder.helper (package:dev_compiler/src/dependency_graph.dart:480)
#26     IterableBase.forEach (dart:collection/iterable.dart:229)
#27     visitInPostOrder.helper (package:dev_compiler/src/dependency_graph.dart:479)
#28     IterableBase.forEach (dart:collection/iterable.dart:229)
#29     visitInPostOrder.helper (package:dev_compiler/src/dependency_graph.dart:479)
#30     IterableBase.forEach (dart:collection/iterable.dart:229)
#31     visitInPostOrder.helper (package:dev_compiler/src/dependency_graph.dart:479)
#32     visitInPostOrder (package:dev_compiler/src/dependency_graph.dart:482)
#33     rebuild (package:dev_compiler/src/dependency_graph.dart:435)
#34     Compiler.run (package:dev_compiler/devc.dart:226)
#35     main (http://localhost:63550/devc.dart:42)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
~/Code/mojo/sky/sdk/lib/framework[master] $ dartdevc fn2.dart 

```

**Comment by jmesserly** [comment]
yeah, things tend to go a little haywire if names are not resolved. I think we're supposed to be aborting Checker if Analyzer finds certain fatal errors, but we don't.

Although in this case, we can probably just fix the problem in rules.isDynamicTarget.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1165823002/

**Comment by jmesserly** [comment]
first fix broke tests ... here's the working one https://codereview.chromium.org/1161603009/

**Comment by sethladd** [comment]
Thanks!
