### ISSUE TITLE
Recent analyzer versions (0.26.4, 0.27.0) break the build

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#393]
Version 0.26.2+1 is fine, while [0.26.3 only seems to exhibits a language test failure](https://travis-ci.org/dart-lang/dev_compiler/builds/95795008).

Getting the following trace (from [this travis execution](https://travis-ci.org/dart-lang/dev_compiler/builds/95794284)):
```
AnalysisException: Cannot compute LIBRARY_ELEMENT for /home/travis/build/dart-lang/dev_compiler/tool/generated_sdk/lib/core/core.dart
Caused by Unexpected exception while performing ResolveUnitTask for source /home/travis/build/dart-lang/dev_compiler/tool/generated_sdk/lib/internal/iterable.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:18)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:681:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:647:12)
#6      AnalysisContextImpl.typeProvider (package:analyzer/src/context/context.dart:486:34)
#7      CodeGenerator.CodeGenerator (package:dev_compiler/src/codegen/code_generator.dart:26:48)
#8      JSGenerator.JSGenerator (package:dev_compiler/src/codegen/js_codegen.dart:3431:44)
#9      BatchCompiler.BatchCompiler (package:dev_compiler/src/compiler.dart:111:20)
#10     compile (package:dev_compiler/src/compiler.dart:69:21)
#11     main (file:///home/travis/build/dart-lang/dev_compiler/bin/dartdevc.dart:49:10)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Caused by RangeError (index): Invalid value: Only valid value is 0: -1
#0      List.[] (dart:core-patch/array.dart:11)
#1      StaticTypeAnalyzer._inferMethodInvocationGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1850:43)
#2      StaticTypeAnalyzer._inferMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:1814:9)
#3      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:743:7)
#4      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12370:41)
#5      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:11832:10)
#6      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12370:41)
#7      ScopedVisitor.safelyVisit (package:analyzer/src/generated/resolver.dart:12779:12)
#8      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:11874:5)
#9      PropertyAccess.accept (package:analyzer/src/generated/ast.dart:15141:41)
#10     ScopedVisitor.safelyVisit (package:analyzer/src/generated/resolver.dart:12779:12)
#11     ResolverVisitor.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:11070:5)
#12     AssignmentExpression.accept (package:analyzer/src/generated/ast.dart:938:41)
#13     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095:13)
#14     ExpressionStatement.visitChildren (package:analyzer/src/generated/ast.dart:7203:5)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#16     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/src/generated/ast.dart:19855:59)
#17     ExpressionStatement.accept (package:analyzer/src/generated/ast.dart:7199:41)
#18     NodeList.accept (package:analyzer/src/generated/ast.dart:12778:20)
#19     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598:17)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#21     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19775:31)
#22     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12790:23)
#23     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:13193:7)
#24     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:11673:11)
#25     IfStatement.accept (package:analyzer/src/generated/ast.dart:9443:41)
#26     NodeList.accept (package:analyzer/src/generated/ast.dart:12778:20)
#27     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598:17)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#29     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19775:31)
#30     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12790:23)
#31     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:13193:7)
#32     ResolverVisitor.visitWhileStatement (package:analyzer/src/generated/resolver.dart:12002:11)
#33     WhileStatement.accept (package:analyzer/src/generated/ast.dart:20601:41)
#34     NodeList.accept (package:analyzer/src/generated/ast.dart:12778:20)
#35     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598:17)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#37     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19775:31)
#38     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12790:23)
#39     Block.accept (package:analyzer/src/generated/ast.dart:3594:41)
#40     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095:13)
#41     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677:5)
#42     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#43     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:19778:55)
#44     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:12802:35)
#45     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:11144:35)
#46     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673:41)
#47     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095:13)
#48     MethodDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:12182:5)
#49     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11844:10)
#50     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/src/generated/ast.dart:19950:55)
#51     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:13176:35)
#52     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:11810:35)
#53     MethodDeclaration.accept (package:analyzer/src/generated/ast.dart:12173:41)
#54     NodeList.accept (package:analyzer/src/generated/ast.dart:12778:20)
#55     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:12871:18)
#56     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:12848:11)
#57     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:11186:34)
#58     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349:41)
#59     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:11274:23)
#60     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968:41)
#61     ResolveUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4638:10)
#62     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310:9)
#63     AnalysisTask.perform (package:analyzer/task/model.dart:210:7)
#64     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272:10)
#65     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:18)
#66     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:681:14)
#67     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:647:12)
#68     AnalysisContextImpl.typeProvider (package:analyzer/src/context/context.dart:486:34)
#69     CodeGenerator.CodeGenerator (package:dev_compiler/src/codegen/code_generator.dart:26:48)
#70     JSGenerator.JSGenerator (package:dev_compiler/src/codegen/js_codegen.dart:3431:44)
#71     BatchCompiler.BatchCompiler (package:dev_compiler/src/compiler.dart:111:20)
#72     compile (package:dev_compiler/src/compiler.dart:69:21)
#73     main (file:///home/travis/build/dart-lang/dev_compiler/bin/dartdevc.dart:49:10)
#74     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by vsmenon** [comment]
@leafpetersen was investigating regressions in DDC from the latest analyzer changes.

**Comment by jmesserly** [comment]
FYI, that bug was fixed (I recognize the stack trace): https://github.com/dart-lang/sdk/commit/67306ae65518a68535fab4f3e557f7dfc43a2093

**Comment by leafpetersen** [comment]
I have a CL here which gets us running on bleeding edge:  https://codereview.chromium.org/1554683002/

This requires some fixes from https://github.com/dart-lang/sdk/commit/a5addef3181bcf2576629d334aa6eb6a1322b425  that aren't in the latest pub release of the analyzer.

@bwilkerson - when everyone is back after the holidays, can we get another drop on pub?

**Comment by bwilkerson** [comment]
Yes, of course.
