### ISSUE TITLE
node wrapper for dart:io

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#436]
We can now compile & run on nodejs. But we don't have a dart:io impl.

**Comment by Kleak** [comment]
Hey maybe i can help on this task.

I'm wrapping nodejs with the js package : [nodejs.dart](https://gitlab.com/grimshield/nodejs.dart)
And a beginning of electron : [electron.dart](https://gitlab.com/grimshield/electron.dart)

The only problem i have is that i am not able to launch generated js file in node with this CL 
dartdevc --v8-binary node -o build --modules node example/test_ddc_example.dart

it throw an error:
```
Error: Cannot find module 'dart/_runtime'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/kleak/Work/test_ddc/build/test_ddc_example.js:2:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by vsmenon** [comment]
Have you tried tried preliminary node usage instructions near the end of #485 ?

**Comment by Kleak** [comment]
Nop, thanks, i will retry with this :)

**Comment by jmesserly** [comment]
yeah you may want to sync to "master" as well. The newer compiler won't generate "dart/_runtime" anymore, it should be trying to `require("dart_sdk")`

**Comment by Kleak** [comment]
ok is there a starting point where i can look how to wrap an API ? is there the same as with the js package ?

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27349
