### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/dev_compiler#454]
Unhandled exception:
The null object does not have a getter 'value'.

NoSuchMethodError: method not found: 'value'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ElementAnnotationImpl.constantValue (package:analyzer/src/dart/element/element.dart:1588)
#3      findAnnotation (package:dev_compiler/src/utils.dart:347)
#4      JSCodegenVisitor._getJSExportName (package:dev_compiler/src/codegen/js_codegen.dart:1410)
#5      JSCodegenVisitor._emitTopLevelName (package:dev_compiler/src/codegen/js_codegen.dart:1910)
#6      JSCodegenVisitor._emitTypeName (package:dev_compiler/src/codegen/js_codegen.dart:1895)
#7      JSCodegenVisitor.visitAsExpression (package:dev_compiler/src/codegen/js_codegen.dart:320)
#8      AsExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:527)
#9      JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#10     JSCodegenVisitor.visitArgumentList (package:dev_compiler/src/codegen/js_codegen.dart:2144)
#11     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:406)
#12     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#13     JSCodegenVisitor.visitMethodInvocation (package:dev_compiler/src/codegen/js_codegen.dart:2081)
#14     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7047)
#15     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#16     JSCodegenVisitor.visitExpressionStatement (package:dev_compiler/src/codegen/js_codegen.dart:2246)
#17     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3983)
#18     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#19     JSCodegenVisitor._visitList (package:dev_compiler/src/codegen/js_codegen.dart:3458)
#20     JSCodegenVisitor.visitBlock (package:dev_compiler/src/codegen/js_codegen.dart:2035)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1248)
#22     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#23     JSCodegenVisitor._visitScope (package:dev_compiler/src/codegen/js_codegen.dart:3096)
#24     JSCodegenVisitor.visitIfStatement (package:dev_compiler/src/codegen/js_codegen.dart:3106)
#25     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5509)
#26     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#27     JSCodegenVisitor._visitList (package:dev_compiler/src/codegen/js_codegen.dart:3458)
#28     JSCodegenVisitor.visitBlockFunctionBody (package:dev_compiler/src/codegen/js_codegen.dart:2028)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195)
#30     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#31     JSCodegenVisitor._emitConstructorBody (package:dev_compiler/src/codegen/js_codegen.dart:1133)
#32     JSCodegenVisitor._emitConstructor (package:dev_compiler/src/codegen/js_codegen.dart:1065)
#33     JSCodegenVisitor._emitClassMethods (package:dev_compiler/src/codegen/js_codegen.dart:664)
#34     JSCodegenVisitor.visitClassDeclaration (package:dev_compiler/src/codegen/js_codegen.dart:433)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1796)
#36     JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3448)
#37     JSCodegenVisitor._emitModuleItem (package:dev_compiler/src/codegen/js_codegen.dart:229)
#38     ModuleItemLoadOrder.loadDeclaration (package:dev_compiler/src/codegen/js_module_item_order.dart:148)
#39     JSCodegenVisitor.emitLibrary (package:dev_compiler/src/codegen/js_codegen.dart:170)
#40     JSGenerator.generateLibrary (package:dev_compiler/src/codegen/js_codegen.dart:3728)
#41     BatchCompiler._processPending (package:dev_compiler/src/compiler.dart:185)
#42     BatchCompiler._compileSource (package:dev_compiler/src/compiler.dart:154)
#43     BatchCompiler._compileFromUri (package:dev_compiler/src/compiler.dart:145)
#44     BatchCompiler.compileFromUriString (package:dev_compiler/src/compiler.dart:133)
#45     Object&ListMixin.forEach (dart:collection/list.dart:63)
#46     BatchCompiler.run (package:dev_compiler/src/compiler.dart:124)
#47     compile (package:dev_compiler/src/compiler.dart:69)
#48     main (http://localhost:61716/dartdevc.dart:49)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by kzhdev** [comment]
Created an issue in SDK repo:
https://github.com/dart-lang/sdk/issues/25779
