### ISSUE TITLE
generator issues on chrome canary

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#483]
Chrome Canary on Travis has a slightly newer build than my mac. It might be coincidence, but it seems to have a new generator-related failure: https://travis-ci.org/dart-lang/dev_compiler/jobs/119365119
```
Chrome 51.0.2694 (Linux 0.0.0) language async_return_types_test_nestedFuture_multi FAILED
	Uncaught Uncaught Error: TypeError: Generator is already running
	Stack Trace:
	TypeError: Generator is already running
	    at next (native)
	    at onValue (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/_runtime.js:261:24)
	    at handleValueCallback (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2425:45)
	    at Function._propagateToListeners (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2506:36)
	    at _Future.[_completeWithValue] (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2347:20)
	    at _AsyncCallbackEntry.(anonymous function).scheduleMicrotask.dart.fn [as callback] (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2380:35)
	    at _asyncRunCallbackLoop (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2645:13)
	    at _asyncRunCallback (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2652:7)
	    at MutationObserver.internalCallback (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/async.js:2715:16) (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/_runtime.js:566)
	Error: Uncaught Uncaught Error: TypeError: Generator is already running
	Stack Trace:
	TypeError: Generator is already running
	    at next (native)
	    at onValue (base/lib/runtime/dart/_runtime.js?4ddd3f68b210aa7e315aaf66f412317a25739a8f:261:24)
	    at handleValueCallback (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2425:45)
	    at Function._propagateToListeners (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2506:36)
	    at _Future.[_completeWithValue] (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2347:20)
	    at _AsyncCallbackEntry.(anonymous function).scheduleMicrotask.dart.fn [as callback] (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2380:35)
	    at _asyncRunCallbackLoop (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2645:13)
	    at _asyncRunCallback (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2652:7)
	    at MutationObserver.internalCallback (base/lib/runtime/dart/async.js?1c226272f42219f13b5107dd522294ec004dae0e:2715:16) (/home/travis/build/dart-lang/dev_compiler/lib/runtime/dart/_runtime.js:566)
```

This could be a V8 bug, as many of our generator tests are passing, and the failures are sometimes in very simple cases:
```dart
  // ...
  group("basic", () {
    test("async w/o await", () {
      f() async { return id(42); }
      return expect42(f());
    });
  // ...

// Attempt to obfuscates value to avoid too much constant folding.
id(v) {
  try {
    if (v != null) throw v;
  } catch (e) {
    return e;
  }
  return null;
}
```

it's still passing on Electron. `51.0.2693.2` seems to pass, `51.0.2694` seems to fail. My local machine is Mac x64 Chrome, Travis runs on Linux (not sure x86 or x64) so that could be related?

**Comment by jmesserly** [comment]
NOTE: I might be wrong about which test is failing. In this log it looks like different failures:
https://travis-ci.org/dart-lang/dev_compiler/jobs/119365119

That could either support the V8 bug theory (flaky codegen?) or it could mean we have a few tests that are consistently failing, due to incorrect use of generators, and it is simply the log that is misleading.

**Comment by vsmenon** [comment]
This was a transient Chrome bug I think.
