### ISSUE TITLE
package summaries are not working yet

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#495]
We seem to get a crash in InputPackagesResultProvider. Maybe I didn't set something up right?

This is using the branch https://github.com/dart-lang/dev_compiler/tree/fix_summaries. The master branch doesn't set up the context to load them at all.

CC @sigmundch ... we think there may be another bug with how package URIs are working. Also ".sum" vs ".strong.sum", as DDC only strips one file extension.

>    dartdevc arguments: compile -o test/command/hello.js -s test/command/hello_lib.sum test/command/hello.dart

```
The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      InputPackagesResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:90:45)
#3      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:520:52)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#5      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:518:42)
#6      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:733:21)
#7      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:867:17)
#8      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:400:35)
#9      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:833:31)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#11     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:825:44)
#12     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:106:26)
#13     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:672:14)
#14     AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1270:12)
#15     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:71:34)
#16     CompileCommand.run (package:dev_compiler/src/compiler/command.dart:41:36)
#17     CommandRunner.runCommand.<anonymous closure> (package:args/command_runner.dart:176:22)
#18     Future.Future.sync (dart:async/future.dart:168)
#19     CommandRunner.runCommand (package:args/command_runner.dart:129:16)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:103:29)
#21     Future.Future.sync (dart:async/future.dart:168)
#22     CommandRunner.run (package:args/command_runner.dart:103:11)
#23     main.<main_async_body> (file:///Users/jmesserly/src/dev_compiler/bin/dartdevc.dart:46:18)
#24     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

**Comment by jmesserly** [comment]
this is fixed now. it was not setting up the URI resolver correctly, so we got in a weird state where we tried to provide results even though it was a FileBasedSource (instead of an InSummarySource)
