### ISSUE TITLE
usage exceptions are not caught correctly 

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#513]
When I use ./bin/dartdevc incorrect I get a stack trace:

```
./bin/dartdevc.dart oops
<usage info>
Run "dartdevc help <command>" for more information about a command.
#0      Command.usageException (package:args/command_runner.dart:356:7)
#1      CompileCommand.run (package:dev_compiler/src/compiler/command.dart:39:7)
#2      CommandRunner.runCommand.<anonymous closure> (package:args/command_runner.dart:176:22)
#3      Future.Future.sync (dart:async/future.dart:168)
#4      CommandRunner.runCommand (package:args/command_runner.dart:129:16)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:103:29)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      CommandRunner.run (package:args/command_runner.dart:103:11)
#8      _runCommand (file:///Users/jmesserly/src/dev_compiler/bin/dartdevc.dart:59:12)
#9      main.<main_async_body> (file:///Users/jmesserly/src/dev_compiler/bin/dartdevc.dart:50:16)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
<snip>
```

**Comment by jmesserly** [comment]
@jakemac53 could this be related to the recent worker changes ?

**Comment by jmesserly** [comment]
the same thing happens if you code has a compile error. We print then errors (good) then crash with a stack trace (bad)

**Comment by jakemac53** [comment]
Yep, looks like it is, the try/catch isn't working because `CommanRunner.run` actually returns a future.

**Comment by jmesserly** [comment]
ah yeah ... I think we were using the try/catch around an `await` previously
