### ISSUE TITLE
Function subtyping bug

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#588]
```dart
import 'bar.dart' as bar;

typedef int Int2Int(int x);

void foo(List<Int2Int> list) {
  list.forEach((f) => print(f(42)));
}

void main() {
  var l = <Function>[];
  foo(l);
}
```

generates the following error:

```
/Users/vsm/ddctest/dart_sdk.js:1573
    if (args1.length > args2.length) {
             ^
TypeError: Cannot read property 'length' of undefined
    at dart.isFunctionSubtype (/Users/vsm/ddctest/dart_sdk.js:1573:14)
    at dart._isSubtype (/Users/vsm/ddctest/dart_sdk.js:1655:19)
    at dart.isClassSubType (/Users/vsm/ddctest/dart_sdk.js:1677:27)
    at definitive (/Users/vsm/ddctest/dart_sdk.js:1686:25)
    at dart.isClassSubType (/Users/vsm/ddctest/dart_sdk.js:1703:27)
    at dart._isSubtype (/Users/vsm/ddctest/dart_sdk.js:1649:25)
    at dart.isSubtype.dart._subtypeMemo (/Users/vsm/ddctest/dart_sdk.js:2254:68)
    at null.isSubtype (/Users/vsm/ddctest/dart_sdk.js:1627:16)
    at dart.strongInstanceOf (/Users/vsm/ddctest/dart_sdk.js:1160:23)
    at dart.check (/Users/vsm/ddctest/dart_sdk.js:1185:23)
```

**Comment by vsmenon** [comment]
Note, this should throw.  The VM throws:
```
List<Function> is not a subtype of type List<Int2Int>
```
