### ISSUE TITLE
Fix travis against analyzer tip

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#618]
We're currently failing against analyzer tip-of-tree with (see https://travis-ci.org/dart-lang/dev_compiler/jobs/149241488):

```
*** Compiling SDK to JavaScript
00:43 +1895 -1: codegen dartdevc language/internal_library_test_02_multi                           
  AnalysisException: Cannot compute DART_ERRORS for dart:_foreign_helper
```

This is a negative test:

```dart
library internal_library_test;

import 'dart:core'; // This loads 'dart:_foreign_helper' and 'patch:core'.
import 'dart:_foreign_helper'; /// 01: compile-time error

part 'dart:_foreign_helper'; /// 02: compile-time error
```

It looks like we're not catching the error properly now.

**Comment by vsmenon** [comment]
@leafpetersen 

Is this possibly related to recent warnings around part files?

**Comment by vsmenon** [comment]
Here's the full stack from DDC.  It's throwing inside the analyzer.  @bwilkerson - anything change around this?  Running dartanalyzer directly seems to work fine.

```
00:44 +1895 -1: codegen dartdevc language/internal_library_test_02_multi                           
  AnalysisException: Cannot compute DART_ERRORS for dart:_foreign_helper
  Caused by 62 unmatched elements found:
    String typeDescription
    JS_GET_FLAG(String name) → bool
    dynamic args
    [dynamic arg9]
    [dynamic arg6]
    [dynamic arg0]
    JS_FUNCTION_TYPE_OPTIONAL_PARAMETERS_TAG() → String
    [dynamic arg11]
    [dynamic arg2]
    [dynamic arg10]
    class _Rest
    String codeTemplate
    String name
    JS_STRING_CONCAT(String a, String b) → String
    JS_EFFECT(Function code) → void
    spread(dynamic args) → dynamic
    dynamic isolate
    JS_GET_NAME(String name) → String
    String typeDescription
    [dynamic arg5]
    String name
    String name
    JS_FUNCTION_TYPE_RETURN_TYPE_TAG() → String
    JS_FUNCTION_TYPE_VOID_RETURN_TAG() → String
    String code
    JS_OPERATOR_AS_PREFIX() → String
    [dynamic arg3]
    String a
    JS_FUNCTION_CLASS_NAME() → String
    [dynamic arg7]
    _Rest rest
    JS_FUNCTION_TYPE_REQUIRED_PARAMETERS_TAG() → String
    JS_NULL_CLASS_NAME() → String
    JS_OPERATOR_IS_PREFIX() → String
    String b
    [dynamic arg1]
    JS_SIGNATURE_NAME() → String
    JS_DART_OBJECT_CONSTRUCTOR() → dynamic
    JS_CURRENT_ISOLATE() → dynamic
    JS_FUNCTION_TYPE_NAMED_PARAMETERS_TAG() → String
    JS_SET_CURRENT_ISOLATE(dynamic isolate) → void
    JS(String typeDescription, String codeTemplate, [dynamic arg0, dynamic arg1, dynamic arg2, dynamic arg3, dynamic arg4, dynamic arg5, dynamic arg6, dynamic arg7, dynamic arg8, dynamic arg9, dynamic arg10, dynamic arg11]) → dynamic
    Type type
    JS_OBJECT_CLASS_NAME() → String
    class JSExportName
    JS_FUNCTION_TYPE_TAG() → String
    String name
    abstract class IsolateContext
    get isolateStatics → dynamic
    JS_IS_INDEXABLE_FIELD_NAME() → String
    class JS_CONST
    dynamic isolate
    JS_EMBEDDED_GLOBAL(String typeDescription, String name) → dynamic
    [dynamic arg4]
    Function code
    JS_CREATE_ISOLATE() → dynamic
    JS_CURRENT_ISOLATE_CONTEXT() → IsolateContext
    Function function
    JS_INTERCEPTOR_CONSTANT(Type type) → dynamic
    JS_CALL_IN_ISOLATE(dynamic isolate, Function function) → dynamic
    JS_TYPEDEF_TAG() → String
    [dynamic arg8]
  
  #0      DeclarationResolver._validateResolution (package:analyzer/src/generated/resolver.dart:2846:7)
  #1      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2261:5)
  #2      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1100:33)
  #3      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338:9)
  #4      AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
  #5      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
  #6      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
  #7      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:714:14)
  #8      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:662:12)
  #9      ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:116:31)
```

**Comment by jmesserly** [comment]
could be because we're compiling against DDC's SDK, not Dart VM (Analyzer used to default to VM under most circumstances, not sure if that's changed).

**Comment by leafpetersen** [comment]
This doesn't look similar to the part file issue.  That just issued a standard warning, that turned (briefly) into a standard error and needed to be turned back.

**Comment by jmesserly** [comment]
@vsmenon a lot of those `JS_FUNCTION_TYPE_RETURN_TYPE_TAG` are metadata annotations from Dart2js that are probably removed/unused in DDC.

**Comment by jmesserly** [comment]
I'm guessing this is obsolete.
